---
ID: "f43073aa-1beb-4993-8b9a-8cb3c52a3754"
Parent: "14c6e3d7-b08c-4e89-80d3-a342cf24059d"
Template: "14c6e3d7-b08c-4e89-80d3-a342cf24059d"
Path: /sitecore/templates/LiveList/Content Types/Live List Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170403T083637Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
