---
ID: "8e8bf782-4093-4714-9099-125f181ec506"
Parent: "967cfd6c-b296-4b04-a130-9fe029aa5fca"
Template: "967cfd6c-b296-4b04-a130-9fe029aa5fca"
Path: /sitecore/templates/LiveList/Base Templates/_LiveListItem/__Standard Values
DB: master
SharedFields:
- ID: "57cbca4c-8c94-446c-b8ca-7d8dc54f4285"
  Hint: __Validate Button Validation Rules
  Type: TreelistEx
  Value: 
- ID: "86b52eef-078e-4d9e-80bf-888287070e6c"
  Hint: __Workflow Validation Rules
  Type: TreelistEx
  Value: 
- ID: "b7e5b151-b145-4ced-85c5-fbdb566dfa4d"
  Hint: __Validator Bar Validation Rules
  Type: TreelistEx
  Value: 
- ID: "c2f5b2b5-71c1-431e-bf7f-dbdc1e5a2f83"
  Hint: __Quick Action Bar Validation Rules
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170304T181323Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
